FROM golang:1.23-alpine

# Install tools required for running tests and CGO dependencies
RUN apk add --no-cache \
    bash \
    make \
    git \
    curl \
    tmux \
    vim \
    asciinema \
    ttyd \
    gcc \
    musl-dev

WORKDIR /src

COPY go.mod go.sum ./
ENV GOTOOLCHAIN=local
ENV CGO_ENABLED=1
RUN go mod download

COPY . .

CMD ["go", "test", "./..."]
