FROM golang:1.24-alpine

# Install tools required for running tests
RUN apk add --no-cache \
    bash \
    make \
    git \
    curl \
    tmux \
    vim \
    asciinema \
    ttyd

WORKDIR /src

COPY go.mod go.sum ./
ENV GOTOOLCHAIN=local
RUN go mod download

COPY . .

CMD ["go", "test", "./..."]
