#!/bin/bash
# REPLbot demo script to show how to build a simple custom REPL.
#
# Scripts are executed as "./script run <id>" to start the REPL,
# and as "./script kill <id>" to stop it.
#
# This script does not need an explicit "kill" behavior, since it's
# a simple bash script. If you spawn other processes you may want to
# clean up after yourself though, particularly for Docker containers.

case "$1" in
  run)
    echo "Welcome to the demo REPL!"
    echo "This is a simple demonstration script."
    echo
    echo "You are now in a bash shell. Try commands like:"
    echo "  - date"
    echo "  - uptime"
    echo "  - echo hello world"
    echo "  - pwd"
    echo "  - ls"
    echo
    echo "Type 'exit' to quit"
    echo
    
    # Start bash in interactive mode
    exec /bin/bash --norc --noprofile -i 2>&1
    ;;
  kill)
    ;;
  *) echo "Syntax: $0 (run|kill) ID"; exit 1 ;;
esac
