name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build test image
        run: docker build -t replbot-test -f Dockerfile.test .
      - name: Run tests, formatting, vetting and linting
        run: docker run --rm replbot-test make check
      - name: Run and upload coverage to codecov.io
        run: docker run --rm replbot-test make coverage coverage-upload
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install security tools
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install github.com/google/go-licenses@latest
      - name: Run govulncheck
        run: govulncheck ./...
      - name: Run gosec
        run: gosec ./...
      - name: Check licenses
        run: go-licenses check ./...
